/* This file is auto-generated by @tanstack/router-plugin on dev/build.
   The stub below makes the first install typecheck cleanly. */
import { createRootRoute, createRoute } from "@tanstack/react-router";

const rootRoute = createRootRoute();
const indexRoute = createRoute({ getParentRoute: () => rootRoute, path: "/" });
const usersRoute = createRoute({ getParentRoute: () => rootRoute, path: "/users" });
const loginRoute = createRoute({ getParentRoute: () => rootRoute, path: "/login" });

export const routeTree = rootRoute.addChildren([indexRoute, usersRoute, loginRoute]);
